### ISSUE TITLE
trained_agents.zip is empty

### ISSUE THREAD

**Issue by nik-suri** [RLMA2019/RLMA#2]
When I unzip 'trained_agents.zip', the resulting 'trained_agents/' folder is empty. Could you please include the agents that you trained? Running the command `python A2C_Minimalistic_Attack.py    -g   'Pong'  -a   'a2c'   -n   5   -t   0.9   -r   'a2crun'` results in the following error:

```
Traceback (most recent call last):
  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\usr\Documents\User\GitHub\RLMA\A2C_Minimalistic_Attack.py", line 77, in main
    model = DQN.load("trained_agents/{}/{}NoFrameskip-v4".format(method,game))
  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\site-packages\stable_baselines\common\base_class.py", line 914, in load
    data, params = cls._load_from_file(load_path, custom_objects=custom_objects)
  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\site-packages\stable_baselines\common\base_class.py", line 579, in _load_from_file
    raise ValueError("Error: the file {} could not be found".format(load_path))
ValueError: Error: the file trained_agents/'a2c'/'Pong'NoFrameskip-v4 could not be found
```

**Comment by RLMA2019** [comment]
The pkl files for the well-trained policies have been re-uploaded.
